name: 'Dance! -Houston'
favicon: null
layout_spectrum: 0.74936
typography_spectrum: 0.70425
title: Dance Houston
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f03f09'
    - '#666666'
    - '#d0d0d0'
    - '#9e9e9e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
